### ISSUE TITLE
Build instructions unclear

### ISSUE THREAD

**Issue by simonjosefsson** [jurisv/extdirect.examples#27]
Hi! I'm brand new to sencha/extjs and have difficulties following the instructions...

I've done the following (on win 8.1):
* Installed Sencha Cmd v5.1, it's in my path
* Downloaded [extjs 4.2](http://www.sencha.com/products/extjs/download/ext-js-4.2.1)
* Ran `sencha generate app DemoExtJs ..\DemoExtJs` within the `ext-4.2.1.883` folder
* Cloned this repo
* Replaced the `ext` folder in `extdirect.examples\client\DemoExtJs` with the generated one

Running `sencha app refresh` in `extdirect.examples\client\DemoExtJs` results in:
<pre>
Sencha Cmd v5.1.1.39
[INF] Processing Build Descriptor : default
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExNotFound: Required property file [path]\extdirect.examples\client\DemoExtJs\.sencha\app\development.defaults.properties does not exist
[ERR]
[ERR] Total time: 0 seconds
[ERR] The following error occurred while executing this line: [path]\bin\Sencha\Cmd\5.1.1.39\plugins\ext\4.2\plugin.xml:394:
The following error occurred while executing this  line: [path]\extdirect.examples\client\DemoExtJs\.sencha\app\init-impl.xml:62:
com.sencha.exceptions.ExNotFound: Required property file [path]\extdirect.examples\client\DemoExtJs\.sencha\app\development.defaults.properties does not exist
</pre>

Should I use another combo of framework and sencha cmd?
Or have I simply misread the instructions? (they are a bit vague for someone not familiar with extjs)
Thanks

**Comment by jurisv** [comment]
Just tested locally. There is nothing wrong with the documentation or code.
The last line which you didn't post says :

    [ERR] 
    The application was last modified by an older version of Sencha Cmd (4.0.4.84)
    the current is 5.1.0.26.
    Please run "sencha app upgrade" to update to 5.1.0.26.
You have to upgrade project to work with latest Sencha CMD (5.x) by issuing the command: sencha app upgrade
